# Generated by Django 4.2.4 on 2023-08-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minchoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies'
            },
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('nuget_id', 'version'),
                                               name='id_and_version_uniq'),
        ),
        migrations.RemoveField(
            model_name='package',
            name='version_download_count',
        ),
        migrations.DeleteModel(name='PackageVersionDownloadCount',),
    ]
